### ISSUE TITLE
When building, Fsecure detects LEDSGui.exe as ramsonware

### ISSUE THREAD

**Issue by BrianLima** [sottam/LedsGUI#1]
Not sure why, if you need more tests tell me.

![image](https://user-images.githubusercontent.com/1337383/36444125-703f4732-1659-11e8-9669-dba62e4e7163.png)
https://www.f-secure.com/v-descs/ransomware.shtml

**Comment by sottam** [comment]
It is odd... as you can see, everything is open source here. there is no malicious code... However, i am working on a new realease. it is almost done. Once it is finished i will publish it here and I hope this false positive will be gone!
